spring.config.import=optional:file:.env[properties]
camel.component.salesforce.authentication-type=${SALESFORCE_AUTHENTICATION_TYPE:CLIENT_CREDENTIALS}
camel.component.salesforce.client-id=${SALESFORCE_CLIENT_ID}
camel.component.salesforce.client-secret=${SALESFORCE_CLIENT_SECRET}
camel.component.salesforce.user-name=${SALESFORCE_USERNAME}
camel.component.salesforce.password=${SALESFORCE_PASSWORD}
camel.component.salesforce.login-url=${SALESFORCE_LOGIN_URL:https://login.salesforce.com}

management.endpoints.web.base-path=/observe
management.server.port=9876
management.endpoint.health.probes.enabled=true

# server.port=3000 if 8080 port is busy