name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: abdocker409/springboot-app-14-09-2026
  DEPLOYMENT_NAME: testdemo
  CONTAINER_NAME: testdemo
  APP_PORT: 8080

jobs:

  build-push-deploy:

    runs-on: ubuntu-latest

    steps:

      # =========================================================
      # 1. Checkout Code
      # =========================================================

      - name: Checkout code
        uses: actions/checkout@v4


      # =========================================================
      # 2. Setup Java 21
      # =========================================================

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven


      # =========================================================
      # 3. Build Spring Boot Application
      # =========================================================

      - name: Maven Build
        run: |
          mvn clean package -DskipTests


      # =========================================================
      # 4. Login to Docker Hub
      # =========================================================

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # =========================================================
      # 5. Build Docker Image
      # =========================================================

      - name: Build Docker Image
        run: |
           docker build \
           -t $IMAGE_NAME:${{ github.run_number }} \
           -t $IMAGE_NAME:latest \
           .


      # =========================================================
      # 6. Push Docker Image
      # =========================================================

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ github.run_number }}
          docker push $IMAGE_NAME:latest

      # =========================================================
      # 7. Install OpenShift CLI
      # =========================================================

      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1


      # =========================================================
      # 8. Login to OpenShift
      # =========================================================

      - name: Login to OpenShift
        run: |
          oc login \
            --server="${{ secrets.OPENSHIFT_SERVER }}" \
            --token="${{ secrets.OPENSHIFT_TOKEN }}"


      # =========================================================
      # 9. Select OpenShift Project
      # =========================================================

      - name: Select OpenShift Project
        run: |
          oc project "${{ secrets.OPENSHIFT_NAMESPACE }}"


      # =========================================================
      # 10. Check Deployment
      # =========================================================

      - name: Check Deployment
        id: check-deployment
        run: |

          if oc get deployment "$DEPLOYMENT_NAME" >/dev/null 2>&1; then

            echo "Deployment $DEPLOYMENT_NAME already exists."

            echo "exists=true" >> "$GITHUB_OUTPUT"

          else

            echo "Deployment $DEPLOYMENT_NAME does not exist."

            echo "exists=false" >> "$GITHUB_OUTPUT"

          fi


      # =========================================================
      # 11. Create Deployment + Service
      # =========================================================

      - name: Create Deployment
        if: steps.check-deployment.outputs.exists == 'false'
        run: |

          echo "Deployment does not exist."

          echo "Creating Deployment and Service..."

          oc apply -f k8s/deployment.yaml

          echo "Deployment and Service created."


      # =========================================================
      # 12. Update Existing Deployment
      # =========================================================

      - name: Update Existing Deployment
        if: steps.check-deployment.outputs.exists == 'true'
        run: |

          echo "Deployment already exists."

          echo "Updating image..."

          oc set image deployment/$DEPLOYMENT_NAME \
            $CONTAINER_NAME=$IMAGE_NAME:${{ github.run_number }}

          echo "Image updated successfully."


      # =========================================================
      # 13. Verify Container Name
      # =========================================================



      - name: Verify Deployment Configuration
        run: |

          echo "Deployment:"
          oc get deployment $DEPLOYMENT_NAME

          echo ""
          echo "Container:"
          oc get deployment $DEPLOYMENT_NAME \
            -o jsonpath='{.spec.template.spec.containers[*].name}'

          echo ""

          echo "Image:"
          oc get deployment $DEPLOYMENT_NAME \
            -o jsonpath='{.spec.template.spec.containers[*].image}'

          echo ""


      # =========================================================
      # 14. Wait for Rollout
      # =========================================================

      - name: Wait for Rollout
        run: |

          echo "Waiting for deployment rollout..."

          oc rollout status deployment/$DEPLOYMENT_NAME \
            --timeout=180s


      # =========================================================
      # 15. Verify Deployment
      # =========================================================

      - name: Verify Deployment
        run: |

          echo "=============================="
          echo "DEPLOYMENT"
          echo "=============================="

          oc get deployment $DEPLOYMENT_NAME


          echo ""
          echo "=============================="
          echo "PODS"
          echo "=============================="

          oc get pods \
            -l app=$DEPLOYMENT_NAME


          echo ""
          echo "=============================="
          echo "SERVICE"
          echo "=============================="

          oc get service $DEPLOYMENT_NAME


          echo ""
          echo "=============================="
          echo "IMAGE"
          echo "=============================="

          oc get deployment $DEPLOYMENT_NAME \
            -o jsonpath='{.spec.template.spec.containers[*].image}'

          echo ""